workspace.members = [ "pakka_core", "pakka_macro"]
[package]
name = "pakka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }

[dependencies]
pakka_macro = { path = "pakka_macro" }
tokio = { workspace = true }

[lib]
